# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pynms_rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pynms_rpc.proto',
  package='pynms_api',
  syntax='proto3',
  serialized_pb=_b('\n\x0fpynms_rpc.proto\x12\tpynms_api\x1a\x19google/protobuf/any.proto\":\n\x04Path\x12!\n\x04type\x18\x01 \x01(\x0e\x32\x13.pynms_api.PathType\x12\x0f\n\x07\x65lement\x18\x02 \x03(\t\"[\n\x08Response\x12!\n\x04path\x18\x01 \x01(\x0e\x32\x13.pynms_api.PathType\x12\x1d\n\x04type\x18\x02 \x01(\x0e\x32\x0f.pynms_api.Type\x12\r\n\x05value\x18\x03 \x01(\t\"/\n\nGetRequest\x12!\n\x04path\x18\x02 \x03(\x0e\x32\x13.pynms_api.PathType\"4\n\x0bGetResponse\x12%\n\x08response\x18\x01 \x03(\x0b\x32\x13.pynms_api.Response*\x1f\n\x04Type\x12\x08\n\x04JSON\x10\x00\x12\r\n\tIETF_JSON\x10\x02**\n\x08PathType\x12\t\n\x05XPATH\x10\x00\x12\x13\n\x0fOpenConfig_Path\x10\x01\x32?\n\x07OCPyNMS\x12\x34\n\x03Get\x12\x15.pynms_api.GetRequest\x1a\x16.pynms_api.GetResponseb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='pynms_api.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='JSON', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IETF_JSON', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=313,
  serialized_end=344,
)
_sym_db.RegisterEnumDescriptor(_TYPE)

Type = enum_type_wrapper.EnumTypeWrapper(_TYPE)
_PATHTYPE = _descriptor.EnumDescriptor(
  name='PathType',
  full_name='pynms_api.PathType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='XPATH', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OpenConfig_Path', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=346,
  serialized_end=388,
)
_sym_db.RegisterEnumDescriptor(_PATHTYPE)

PathType = enum_type_wrapper.EnumTypeWrapper(_PATHTYPE)
JSON = 0
IETF_JSON = 2
XPATH = 0
OpenConfig_Path = 1



_PATH = _descriptor.Descriptor(
  name='Path',
  full_name='pynms_api.Path',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='pynms_api.Path.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='element', full_name='pynms_api.Path.element', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=115,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='pynms_api.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='pynms_api.Response.path', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='pynms_api.Response.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='pynms_api.Response.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=208,
)


_GETREQUEST = _descriptor.Descriptor(
  name='GetRequest',
  full_name='pynms_api.GetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='pynms_api.GetRequest.path', index=0,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=257,
)


_GETRESPONSE = _descriptor.Descriptor(
  name='GetResponse',
  full_name='pynms_api.GetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='pynms_api.GetResponse.response', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=311,
)

_PATH.fields_by_name['type'].enum_type = _PATHTYPE
_RESPONSE.fields_by_name['path'].enum_type = _PATHTYPE
_RESPONSE.fields_by_name['type'].enum_type = _TYPE
_GETREQUEST.fields_by_name['path'].enum_type = _PATHTYPE
_GETRESPONSE.fields_by_name['response'].message_type = _RESPONSE
DESCRIPTOR.message_types_by_name['Path'] = _PATH
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['GetRequest'] = _GETREQUEST
DESCRIPTOR.message_types_by_name['GetResponse'] = _GETRESPONSE
DESCRIPTOR.enum_types_by_name['Type'] = _TYPE
DESCRIPTOR.enum_types_by_name['PathType'] = _PATHTYPE

Path = _reflection.GeneratedProtocolMessageType('Path', (_message.Message,), dict(
  DESCRIPTOR = _PATH,
  __module__ = 'pynms_rpc_pb2'
  # @@protoc_insertion_point(class_scope:pynms_api.Path)
  ))
_sym_db.RegisterMessage(Path)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'pynms_rpc_pb2'
  # @@protoc_insertion_point(class_scope:pynms_api.Response)
  ))
_sym_db.RegisterMessage(Response)

GetRequest = _reflection.GeneratedProtocolMessageType('GetRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETREQUEST,
  __module__ = 'pynms_rpc_pb2'
  # @@protoc_insertion_point(class_scope:pynms_api.GetRequest)
  ))
_sym_db.RegisterMessage(GetRequest)

GetResponse = _reflection.GeneratedProtocolMessageType('GetResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETRESPONSE,
  __module__ = 'pynms_rpc_pb2'
  # @@protoc_insertion_point(class_scope:pynms_api.GetResponse)
  ))
_sym_db.RegisterMessage(GetResponse)


import abc
from grpc.beta import implementations as beta_implementations
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

class BetaOCPyNMSServicer(object):
  """<fill me in later!>"""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def Get(self, request, context):
    raise NotImplementedError()

class BetaOCPyNMSStub(object):
  """The interface to which stubs will conform."""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def Get(self, request, timeout):
    raise NotImplementedError()
  Get.future = None

def beta_create_OCPyNMS_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  import pynms_rpc_pb2
  import pynms_rpc_pb2
  request_deserializers = {
    ('pynms_api.OCPyNMS', 'Get'): pynms_rpc_pb2.GetRequest.FromString,
  }
  response_serializers = {
    ('pynms_api.OCPyNMS', 'Get'): pynms_rpc_pb2.GetResponse.SerializeToString,
  }
  method_implementations = {
    ('pynms_api.OCPyNMS', 'Get'): face_utilities.unary_unary_inline(servicer.Get),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)

def beta_create_OCPyNMS_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  import pynms_rpc_pb2
  import pynms_rpc_pb2
  request_serializers = {
    ('pynms_api.OCPyNMS', 'Get'): pynms_rpc_pb2.GetRequest.SerializeToString,
  }
  response_deserializers = {
    ('pynms_api.OCPyNMS', 'Get'): pynms_rpc_pb2.GetResponse.FromString,
  }
  cardinalities = {
    'Get': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'pynms_api.OCPyNMS', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
