vagrant_root = File.dirname(__FILE__)
pynms_grpc_version = "0.0.1"

Vagrant.configure("2") do |config|
  config.vm.define "grpcserver" do |gserver|
    gserver.vm.box = "minimal/jessie64"
    gserver.vm.hostname = "server"
    gserver.vm.box_url = "minimal/jessie64"

    gserver.vm.network :private_network, ip: "2001:db8::1"
    gserver.vm.network :forwarded_port, guest: 22, host: 42022, id: "ssh"

    gserver.vm.provision "file", source: "#{vagrant_root}/../dist/PyNMSGRPC-#{pynms_grpc_version}-py2-none-any.whl", destination: "/tmp/PyNMSGRPC-#{pynms_grpc_version}-py2-none-any.whl"
    gserver.vm.provision "file", source: "#{vagrant_root}/bootstrap/bootstrap_server.sh", destination: "/tmp/srvbootstrap.sh"
    gserver.vm.provision "file", source: "#{vagrant_root}/bootstrap/bootstrap_generic.sh", destination: "/tmp/gbootstrap.sh"
    gserver.vm.provision "shell", inline: "/bin/bash /tmp/gbootstrap.sh"
    gserver.vm.provision "shell", inline: "/bin/bash /tmp/srvbootstrap.sh"


    gserver.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "grpcserver"]
      v.customize ["modifyvm", :id, "--usb", "on"]
      v.customize ["modifyvm", :id, "--usbehci", "off"]
    end
  end

  config.vm.define "grpcclient" do |gclient|
    gclient.vm.box = "minimal/jessie64"
    gclient.vm.hostname = "client"
    gclient.vm.box_url = "minimal/jessie64"

    gclient.vm.network :private_network, ip: "2001:db8::2"
    gclient.vm.network :forwarded_port, guest: 22, host: 42023, id: "ssh"

    gclient.vm.provision "file", source: "#{vagrant_root}/../dist/PyNMSGRPC-#{pynms_grpc_version}-py2-none-any.whl", destination: "/tmp/PyNMSGRPC-#{pynms_grpc_version}-py2-none-any.whl"
    gclient.vm.provision "file", source: "#{vagrant_root}/bootstrap/bootstrap_client.sh", destination: "/tmp/bootstrap.sh"
    gclient.vm.provision "file", source: "#{vagrant_root}/bootstrap/bootstrap_generic.sh", destination: "/tmp/gbootstrap.sh"
    gclient.vm.provision "shell", inline: "/bin/bash /tmp/gbootstrap.sh"
    gclient.vm.provision "shell", inline: "/bin/bash /tmp/bootstrap.sh"

    gclient.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "grpcclient"]
      v.customize ["modifyvm", :id, "--usb", "on"]
      v.customize ["modifyvm", :id, "--usbehci", "off"]
    end
  end
end
